### ISSUE TITLE
Feltöltve

### ISSUE THREAD

**Issue by x-c4mp3r** [Teaching-projects/SZE-FordProg-2020-HTTP#1]
Kedves Máté!

Elkészültem a feladattal, kérlek nézd meg, hogy elfogadható-e ebben a formában.

**Comment by hegyhati** [comment]
Meglestem, jonak tunik,  a readme-ben egy par szot mondjuk orulnek, ha ejtenel (es linkelned) a technologiat, amit hasznaltal, illetve picit meg is mutatni, hogy hol mi van, tehat hol vannak a tokenek, abbol egy peldat megmutatni, ugyanez a nyelvtanra. Amit pl nem ertek, hogy a semantic action-jeid nagy resze az egy string append, amire nem latom, miert van szukseg. 

Illetve egy fontos kerdes; hanyast celzunk most meg?

**Comment by x-c4mp3r** [comment]
A readme-t kiegészítem.
"semantic action-jeid nagy resze az egy string append" -> ezt használom a tényleges content-length feldolgozásra, sajnos a cup és jflex dokumentációban nem találtam rá könnyebb/egyszerűbb megoldást, így az órán bemutatott semantic action felé mentem el.
A célom a 4-es, 5-ös lenne.

**Comment by x-c4mp3r** [comment]
A readme-t kiegészítettem. Így elegendő lesz vagy még jobban fejtsem ki a dolgokat?

**Comment by hegyhati** [comment]
A semantic action-nel semmi baj nincs, de ha csak erre kell, akkro egy int-et is eleg lenne novelgetni a length-tel, nem? De lehet valamit en latok rosszul. Azt az ellenorzest amugy , hogy a jelzett type meg meret rendben van, azt nem lehetne a `http_request ::= start_line http_header_element http_body;` szemantikus akciojaban letesztelni? Amugy az nem kerdes, hogy a 4-es meglegyen, most az otosrol beszelgetunk. A readme kiegeszites jo lett.

**Comment by x-c4mp3r** [comment]
Egy sima int is elég lett volna, csak így menet közben debuggoltam, hogy minden adatot feldolgoz-e és utána nem refaktoráltam.
A `http_request ::= start_line http_header_element http_body; ` is megoldás lenne, csak ott az nem tetszett nekem, ha az alábbit csinálom: `http_request ::= start_line http_header_element http_body:hb {: RESULT = hb; :};` akkor a hb értéke, azaz végeredményben a [RESULT null](https://github.com/Teaching-projects/SZE-FordProg-2020-HTTP/blob/master/debug.png). Ebben az esetben a legalsó szintről kell felépíteni a http_body tartalmát, viszont ennél kényelmesebbnek tűnt, hogy csak a megfelelő terminálisok értékét appendelem a StringBuffer-be.

**Comment by hegyhati** [comment]
De bocsi, nem ertem. en valami ilyesmire gondolok:

```
request ::= header:h body:b  {: if(h.type=body.type and h.size=b.size) .. else valami hibakezeles :} 
```

A technologiaban a RESULT ha jol ertem, a baloldal szintetizalt attributum erteke, amire modnjuk a gyokernel mar semmi szukseg nincs. Meg az aljan sem feltetlenul van mindenhol szukseg ra. Ennel a szabalynal annyi info kell a gyerekektol, hogy az egyiknel mit igertek a tipusra, meretre, a masiknal mi volt a valosagban, es lecsekkolni, hogy az stimmel-e. Tovabbadni feljebb meg nem kell mar semmit, mert ezek az infok eddig voltak erdekesek, felesleges oket tovabb "propagalni" felfele, nem lesznek hasznalva. De lehet valamit rosszul latok.

**Comment by x-c4mp3r** [comment]
Esetleg egy hangouts képernyő megosztással este tudnánk róla egyeztetni?

**Comment by hegyhati** [comment]
NEm igerem, hogy elerheto leszek, de irj majd ram messengeren, es ha oke, akkor csinaljuk. (Hangoutsra csak akkor lepek fel, ha van megbeszelt event.)

**Comment by x-c4mp3r** [comment]
Rendben köszönöm. Azt hiszem közben felfogtam a lényegét a dolognak. Munka után nekiesek és jelzem itt és messengeren a haladás eredményét. Köszönöm!

**Comment by x-c4mp3r** [comment]
Feltettem egy módosítást, mely az alábbiak szerint működik:

    http_request ::= start_line http_header_element:he http_body:hb {:boolean valid = true;
        if(he.getType().equals(hb.getType())) {
            System.out.println("Valid type");
        } else {
            System.out.println("Invalid type");
            valid = false;
        }
        if(he.getSize().equals(hb.getSize())) {
            System.out.println("Valid size");
        } else {
            System.out.println("Invalid size");
            valid = false;
        }
        if(valid) {
           System.out.println("Valid request");
        } else {
           System.out.println("Invalid request");
        }
       :};

**Comment by hegyhati** [comment]
A kimenettel nem volt problemam, de mindegy, rendben lesz ez, zarjuk le otossel, ezek mar reszletkerdesek.  :-)

**Comment by x-c4mp3r** [comment]
Köszönöm szépen! :)
